### ISSUE TITLE
Can't create DB

### ISSUE THREAD

**Issue by 1nkotb** [helviojunior/knowsmore#3]
user@host:~/.local/lib/python3.8/site-packages/Levenshtein$ knowsmore --create-db

KnowsMore v0.1.30 by Helvio Junior
Active Directory, BloodHound, NTDS hashes and Password Cracks correlation tool
https://github.com/helviojunior/knowsmore

 [!] Error: ('Error listing command modules', TypeError("'type' object is not subscriptable"))

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/cmdbase.py", line 57, in list_modules
 [!]        importlib.import_module(f'{base_module}.{modname}')
 [!]    File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
 [!]        return _bootstrap._gcd_import(name[level:], package, level)
 [!]    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
 [!]    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
 [!]    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
 [!]    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
 [!]    File "<frozen importlib._bootstrap_external>", line 848, in exec_module
 [!]    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/cmd/bloodhound.py", line 31, in <module>
 [!]        class Bloodhound(CmdBase):
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/cmd/bloodhound.py", line 818, in Bloodhound
 [!]        def parse_files(self, files: list[BloodhoundFile]):
 [!]    TypeError: 'type' object is not subscriptable
 [!]
 [!]    During handling of the above exception, another exception occurred:
 [!]
 [!]    Traceback (most recent call last):
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/knowsmore.py", line 96, in run
 [!]        o.main()
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/knowsmore.py", line 25, in main
 [!]        Configuration.initialize()
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/config.py", line 47, in initialize
 [!]        Configuration.load_from_arguments()
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/config.py", line 57, in load_from_arguments
 [!]        args = Arguments()
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/args.py", line 20, in __init__
 [!]        self.args = self.get_arguments()
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/args.py", line 56, in get_arguments
 [!]        mod = self.get_module()
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/args.py", line 29, in get_module
 [!]        Arguments.modules = CmdBase.list_modules()
 [!]    File "/home/user/.local/lib/python3.8/site-packages/knowsmore/cmdbase.py", line 79, in list_modules
 [!]        raise Exception('Error listing command modules', e)
 [!]  Exception: ('Error listing command modules', TypeError("'type' object is not subscriptable"))

 [!] Exiting

**Comment by helviojunior** [comment]
Hi @1nkotb, Thanks by the report.

I commited the correction.
