### ISSUE TITLE
Can't sync data to bloodhound neo4j 

### ISSUE THREAD

**Issue by enj5oy** [helviojunior/knowsmore#8]
### Configuration  
impacket version:  
Python version:  Python 3.11.6
Target OS:  Windows 11

knowsmore --bloodhound --sync-to 127.0.0.1:7687 -p
![2023-11-22_22-53](https://github.com/helviojunior/knowsmore/assets/143943083/fdb2fb93-042c-4b49-b159-f39ed3fbc861)

![2023-11-22_22-55](https://github.com/helviojunior/knowsmore/assets/143943083/b434030f-2a7a-407a-b7ab-1fec251e56d3)

**Comment by helviojunior** [comment]
Adjusted
